name: test

on:

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN:  ${{ secrets.PAT }}
       #TARGET_REPOSITORY: ${{ secrets.TR }}
       UPSTREAM_REPOSITORY: ${{ secrets.HKDP }}
       
    #needs: clean
    steps:
      - name: clone
        run: |
          #git config --global --add safe.directory $(pwd)
          git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} TREP
          cd TREP
          mkdir deploy
          git clone https://github.com/${UPSTREAM_REPOSITORY1}.git tmp
          mv tmp/* deploy/
          rm -rf tmp
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push --force  https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }} main
          rm -rf TREP
  
  deploy:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - uses: ./.github
      - uses: ./HK
        with:
          heroku_api_key: ${{ secrets.KEY }}
          heroku_app_name: ${{ secrets.APP }}
          heroku_email: ${{ secrets.MAIL }} 
